name: "Create Prerelease"
description: "A reusable GitHub Action to create a pre-release version."

author: "Sandy Thomson"

inputs:
  github_token:
    description: "Normal gitHub Token for authentication"
    required: true
  release_pat:
    description: "Personal access token for creating a release, so github actions run"
    required: true
  feature_branch:
    description: "PR branch name"
    required: true
  commit_message_keyword:
    description: "Commit prefix to trigger prerelease creation (put in [] brackets)."
    required: false
    default: "[prerelease]"
  trunk_branch:
    description: "Name of the trunk branch (e.g., main or master)."
    required: false
    default: "master"

outputs:
  pre-release-version:
    description: "Created pre-release-version"
    value: ${{ steps.pre_release_script.outputs.pre_release_version }}"

runs:
  using: "composite"
  steps:
    - name: Checkout Action
      uses: actions/checkout@v4
      with:
        repository: scoffable/pr-publish-prerelease-action
        path: ./action-repo

    - name: "Run Pre-Release Script"
      id: pre_release_script
      shell: "bash"
      run: bash ./action-repo/prerelease.sh "${{ inputs.github_token }}" "${{ inputs.commit_message_keyword }}" "${{ inputs.feature_branch }}" "${{ inputs.trunk_branch }}"

#    - name: Create a Release
#      uses: elgohr/Github-Release-Action@v5
#      env:
#        GH_TOKEN: ${{ inputs.release_pat }}
#      with:
#        title: ${{ steps.pre_release_script.outputs.pre_release_version }}"
#        tag: ${{ steps.pre_release_script.outputs.pre_release_version }}"
#        prerelease: true
    - name: Create a Release
      if: ${{ steps.pre_release_script.outputs.pre_release_version != '' }}
      uses: ncipollo/release-action@v1
      with:
        token: ${{ inputs.release_pat }}
        tag: ${{ steps.pre_release_script.outputs.pre_release_version }}
        commit: ${{ inputs.feature_branch }}
        prerelease: true