name: "Create Prerelease"
description: "A reusable GitHub Action to create a pre-release version."

author: "Sandy Thomson"

inputs:
  github_token:
    description: "GitHub Token for authentication."
    required: true
  commit_message:
    description: 'The commit message, typically supplied by (remove "\"): $\{{ github.event.head_commit.message }}'
    required: true
  commit_message_keyword:
    description: "Commit prefix to trigger prerelease creation (put in [] brackets)."
    required: false
    default: "[prerelease]"
  trunk_branch:
    description: "Name of the trunk branch (e.g., main or master)."
    required: false
    default: "master"

runs:
  using: "composite"
  steps:
    - name: Checkout Action
      uses: actions/checkout@v4
      with:
        repository: scoffable/pr-publish-prerelease-action
        path: ./action-repo

    - name: "Run Pre-Release Script"
      shell: "bash"
      run: bash ./action-repo/prerelease.sh "${{ inputs.github_token }}" "${{ inputs.commit_message_keyword }}" "${{ inputs.commit_message }}" "${{ inputs.trunk_branch }}"